# Generated by Django 5.2 on 2025-04-08 01:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_language_alter_user_grade_alter_user_icon_url'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='career',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='del_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='department_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='review.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='my_ditail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='icon_url',
            field=models.TextField(default='default.jpg'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
