# Generated by Django 4.2 on 2025-04-10 01:59

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon_url',
            field=models.ImageField(default='profile_icons/default.jpg', upload_to=account.models.icon_upload_function),
        ),
    ]
