# Generated by Django 4.2 on 2025-04-11 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_review_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good', to='review.review'),
        ),
    ]
