# Generated by Django 4.2 on 2025-04-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_alter_good_review_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priority_idx',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='class',
            name='priority_idx',
            field=models.IntegerField(default=100),
        ),
    ]
