# Generated by Django 4.2 on 2025-04-16 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_category_priority_idx_class_priority_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='review.category'),
        ),
    ]
